google.maps.__gjsload__('infowindow', function(_){var bRa=function(a,b){if(a.nh.size===1){let c=Array.from(a.nh.values())[0];c.Xr!==b.Xr&&(c.set("map",null),a.nh.delete(c))}a.nh.add(b)},dRa=function(a,b,c=!1){var d=a.__gm;a=d.get("panes");d=d.get("innerContainer");b={Gm:a,Nj:_.vC.Nj(),Xy:d,shouldFocus:b,Xr:c};return new cRa(b)},mP=function(a,b){a.container.style.visibility=b?"":"hidden";b&&a.shouldFocus&&(a.focus(),a.shouldFocus=!1);b?eRa(a):a.yh=!1},fRa=function(a){a.Gj.setAttribute("aria-labelledby",a.qh.id)},gRa=function(a){var b=!!a.get("open"),
c=a.get("content");c=b?c:null;if(c===a.sh)mP(a,b&&a.get("position"));else{if(a.sh){let d=a.sh.parentNode;d===a.nh&&d.removeChild(a.sh)}c&&(a.xh=!1,a.nh.appendChild(c));mP(a,b&&a.get("position"));a.sh=c;nP(a)}},oP=function(a){var b=!!a.get("open"),c=a.get("headerContent"),d=!!a.get("ariaLabel"),e=a.get("headerDisabled"),f=!!a.get("isPoi"),g=!e;b=b?c:null;c=f&&e;a.Gj.style.paddingTop=!f&&e?"12px":"0";e=a.Gj;c?_.ix(e,"gm-style-iw-poi"):_.hJ(e,"gm-style-iw-poi");_.Bq.nh&&!_.Bq.th&&(a.nh.style.overflow=
c?"auto":"scroll");b===a.th?a.ph.style.display=g?"":"none":(a.th&&(e=a.th.parentNode,e===a.qh&&e.removeChild(a.th)),b&&(a.xh=!1,a.qh.appendChild(b),g&&!d&&fRa(a)),a.ph.style.display=g?"":"none",a.th=b,nP(a))},nP=function(a){var b=a.getSize();if(b){var c=b.yn;b=b.minWidth;a.Gj.style.maxWidth=_.Jm(c.width);a.Gj.style.maxHeight=_.Jm(c.height);a.Gj.style.minWidth=_.Jm(b);b=!!a.get("headerDisabled");b=!!a.get("isPoi")&&b;a.nh.style.maxHeight=_.Bq.nh?_.Jm(c.height-(b?0:18)):_.Jm(c.height-(b?0:36));pP(a);
a.wh.start()}},hRa=function(a){var b=a.get("pixelOffset")||new _.To(0,0),c=new _.To(a.Gj.offsetWidth,a.Gj.offsetHeight);a=-b.height+c.height+11+60;var d=b.height+60,e=-b.width+c.width/2+60;c=b.width+c.width/2+60;b.height<0&&(d-=b.height);return{top:a,bottom:d,left:e,right:c}},eRa=function(a){!a.yh&&a.get("open")&&a.get("visible")&&a.get("position")&&(_.eo(a,"visible"),a.yh=!0)},pP=function(a){var b=a.get("position");if(b&&a.get("pixelOffset")){var c=hRa(a);let d=b.x-c.left,e=b.y-c.top,f=b.x+c.right;
c=b.y+c.bottom;_.nx(a.anchor,b);b=a.get("zIndex");_.px(a.container,_.Am(b)?b:e+60);a.set("pixelBounds",_.rp(d,e,f,c))}},jRa=function(a,b,c){return b instanceof _.xo?new iRa(a,b,c):new iRa(a,b)},lRa=function(a){a.nh&&a.dj.push(_.ao(a.nh,"pixelposition_changed",()=>{kRa(a)}))},kRa=function(a){var b=a.model.get("pixelPosition")||a.nh&&a.nh.get("pixelPosition");a.qh.set("position",b)},nRa=function(a){a=a.__gm;a.get("IW_AUTO_CLOSER")||a.set("IW_AUTO_CLOSER",new mRa);return a.get("IW_AUTO_CLOSER")},mRa=
class{constructor(){this.nh=new Set}};var cRa=class extends _.io{constructor(a){super();this.sh=this.th=this.uh=null;this.yh=this.xh=!1;this.Xy=a.Xy;this.shouldFocus=a.shouldFocus;this.container=document.createElement("div");this.container.style.cursor="default";this.container.style.position="absolute";this.container.style.left=this.container.style.top="0";a.Gm.floatPane.appendChild(this.container);this.anchor=document.createElement("div");this.container.appendChild(this.anchor);this.rh=document.createElement("div");this.anchor.appendChild(this.rh);
this.Gj=document.createElement("div");this.rh.appendChild(this.Gj);this.Gj.setAttribute("role","dialog");this.Gj.tabIndex=-1;this.ph=document.createElement("div");this.Gj.appendChild(this.ph);this.qh=document.createElement("div");this.ph.appendChild(this.qh);this.Ah=document.createElement("div");this.rh.appendChild(this.Ah);this.nh=document.createElement("div");this.Gj.appendChild(this.nh);_.OHa(this.container);_.ix(this.Gj,"gm-style-iw");_.ix(this.anchor,"gm-style-iw-a");_.ix(this.rh,"gm-style-iw-t");
_.ix(this.Ah,"gm-style-iw-tc");_.ix(this.Gj,"gm-style-iw-c");_.ix(this.ph,"gm-style-iw-chr");_.ix(this.qh,"gm-style-iw-ch");_.ix(this.nh,"gm-style-iw-d");this.set("isPoi",a.Xr);this.qh.setAttribute("id",_.wo());_.Bq.nh&&!_.Bq.th&&(this.Gj.style.paddingInlineEnd="0",this.Gj.style.paddingBottom="0",this.nh.style.overflow="scroll");mP(this,!1);_.Xn(this.container,"mousedown",_.Nn);_.Xn(this.container,"mouseup",_.Nn);_.Xn(this.container,"mousemove",_.Nn);_.Xn(this.container,"pointerdown",_.Nn);_.Xn(this.container,
"pointerup",_.Nn);_.Xn(this.container,"pointermove",_.Nn);_.Xn(this.container,"dblclick",_.Nn);_.Xn(this.container,"click",_.Nn);_.Xn(this.container,"touchstart",_.Nn);_.Xn(this.container,"touchend",_.Nn);_.Xn(this.container,"touchmove",_.Nn);_.$w(this.container,"contextmenu",this,this.Bh);_.$w(this.container,"wheel",this,_.Nn);a=new _.Po(12,12);var b=new _.To(24,24);this.oh=new _.Kr({Vr:a,tt:b,offset:new _.Po(-6,-6),LD:!0,ownerElement:this.ph});this.ph.appendChild(this.oh.element);_.Xn(this.oh.element,
"click",c=>{_.Nn(c);_.eo(this,"closeclick");this.set("open",!1)});this.wh=new _.oq(()=>{!this.xh&&this.get("content")&&this.get("visible")&&(_.eo(this,"domready"),this.xh=!0)},0);this.zh=_.Xn(this.container,"keydown",c=>{c.key!=="Escape"&&c.key!=="Esc"||!this.Gj.contains(document.activeElement)||(c.stopPropagation(),_.eo(this,"closeclick"),this.set("open",!1))})}ariaLabel_changed(){var a=this.get("ariaLabel");a?this.Gj.setAttribute("aria-label",a):(this.Gj.removeAttribute("aria-label"),this.get("headerDisabled")||
fRa(this))}open_changed(){gRa(this);oP(this)}headerContent_changed(){oP(this)}headerDisabled_changed(){oP(this)}content_changed(){gRa(this)}pendingFocus_changed(){this.get("pendingFocus")&&(this.get("open")&&this.get("visible")&&this.get("position")?_.Iq(this.Gj,!0):console.warn("Setting focus on InfoWindow was ignored. This is most likely due to InfoWindow not being visible yet."),this.set("pendingFocus",!1))}dispose(){setTimeout(()=>{document.activeElement&&document.activeElement!==document.body||
(this.uh&&this.uh!==document.body?_.Iq(this.uh,!0)||_.Iq(this.Xy,!0):_.Iq(this.Xy,!0))});this.zh&&_.Rn(this.zh);this.container.parentNode.removeChild(this.container);this.wh.stop();this.wh.dispose()}getSize(){var a=this.get("layoutPixelBounds"),b=this.get("pixelOffset"),c=this.get("maxWidth")||648,d=this.get("minWidth")||0;if(!b)return null;a?(b=a.maxY-a.minY-(11+-b.height),a=a.maxX-a.minX-6,a>=240&&(a-=120),b>=240&&(b-=120)):(a=648,b=654);a=Math.min(a,c);a=Math.max(d,a);a=Math.max(0,a);b=Math.max(0,
b);return{yn:new _.To(a,b),minWidth:d}}pixelOffset_changed(){var a=this.get("pixelOffset")||new _.To(0,0);this.rh.style.right=_.Jm(-a.width);this.rh.style.bottom=_.Jm(-a.height+11);nP(this)}layoutPixelBounds_changed(){nP(this)}position_changed(){this.get("position")?(pP(this),mP(this,!!this.get("open"))):mP(this,!1)}zIndex_changed(){pP(this)}visible_changed(){this.container.style.display=this.get("visible")?"":"none";this.wh.start();if(this.get("visible")){let a=this.oh.element.style.display;this.oh.element.style.display=
"none";this.oh.element.getBoundingClientRect();this.oh.element.style.display=a;eRa(this)}else this.yh=!1}Bh(a){for(var b=!1,c=this.get("content"),d=a.target;!b&&d;)b=d===c,d=d.parentNode;b?_.Hn(a):_.Mn(a)}focus(){this.uh=document.activeElement;var a;_.Bq.xh&&(a=this.nh.getBoundingClientRect());if(this.get("disableAutoPan"))_.Iq(this.Gj,!0);else{var b=_.tx(this.nh);if(b.length){b=b[0];a=a||this.nh.getBoundingClientRect();var c=b.getBoundingClientRect();_.Iq(c.bottom<=a.bottom&&c.right<=a.right?b:this.Gj,
!0)}else _.Iq(this.oh.element,!0)}}};var iRa=class{constructor(a,b,c){this.model=a;this.isOpen=!0;this.nh=this.ph=this.Nh=null;this.dj=[];var d=a.get("shouldFocus");this.qh=dRa(b,d,a.Xr);var e=b.__gm;(d=b instanceof _.xo)&&c?c.then(h=>{this.isOpen&&(this.Nh=h,this.nh=new _.cN(k=>{this.ph=new _.SB(b,h,k,()=>{});h.Fj(this.ph);return this.ph}),this.nh.bindTo("latLngPosition",a,"position"),lRa(this))}):(this.nh=new _.cN,this.nh.bindTo("latLngPosition",a,"position"),this.nh.bindTo("center",e,"projectionCenterQ"),this.nh.bindTo("zoom",e),
this.nh.bindTo("offset",e),this.nh.bindTo("projection",b),this.nh.bindTo("focus",b,"position"),lRa(this));this.rh=d?a.infoWindow.get("logAsInternal")?148284:148285:null;var f=new _.TM(["scale"],"visible",h=>h==null||h>=.3);this.nh&&f.bindTo("scale",this.nh);var g=this.qh;g.set("logAsInternal",!!a.infoWindow.get("logAsInternal"));g.bindTo("ariaLabel",a);g.bindTo("zIndex",a);g.bindTo("layoutPixelBounds",e,"pixelBounds");g.bindTo("disableAutoPan",a);g.bindTo("pendingFocus",a);g.bindTo("maxWidth",a);
g.bindTo("minWidth",a);g.bindTo("content",a);g.bindTo("headerContent",a);g.bindTo("headerDisabled",a);g.bindTo("pixelOffset",a);g.bindTo("visible",f);this.oh=new _.oq(()=>{if(b instanceof _.xo)if(this.Nh){var h=a.get("position");h&&_.cma(b,this.Nh,new _.Eo(h),hRa(g))}else c.then(()=>{this.oh.start()});else(h=g.get("pixelBounds"))?_.eo(e,"pantobounds",h):this.oh.start()},150);if(d){let h=null;this.dj.push(_.ao(a,"position_changed",()=>{var k=a.get("position");!k||a.get("disableAutoPan")||k.equals(h)||
(this.oh.start(),h=k)}))}else a.get("disableAutoPan")||this.oh.start();g.set("open",!0);this.dj.push(_.Pn(g,"domready",()=>{a.trigger("domready")}));this.dj.push(_.Pn(g,"visible",()=>{a.trigger("visible")}));this.dj.push(_.Pn(g,"closeclick",()=>{a.close();a.trigger("closeclick")}));this.dj.push(_.ao(a,"pixelposition_changed",()=>{kRa(this)}));this.rh&&_.P(b,this.rh)}close(){if(this.isOpen){this.isOpen=!1;this.model.trigger("close");for(var a of this.dj)_.Rn(a);this.dj.length=0;this.oh.stop();this.oh.dispose();
this.Nh&&this.ph&&this.Nh.Xl(this.ph);a=this.qh;a.unbindAll();a.set("open",!1);a.dispose();this.nh&&this.nh.unbindAll()}}};_.bm("infowindow",{CJ:function(a){var b=null;_.ao(a,"map_changed",function d(){var e=a.get("map");b&&(b.iF.nh.delete(a),b.rN.close(),b=null);if(e){let f=e.__gm;f.get("panes")?f.get("innerContainer")?(b={rN:jRa(a,e,e instanceof _.xo?f.oh.then(({Nh:g})=>g):void 0),iF:nRa(e)},bRa(b.iF,a)):_.$n(f,"innercontainer_changed",d):_.$n(f,"panes_changed",d)}})}});});
